# Generated by Django 3.1.2 on 2020-10-24 19:16

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('creditLimit', models.PositiveIntegerField(default=0)),
                ('currency_code', models.IntegerField(default=980)),
                ('cashbackType', models.CharField(default=0, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('time', models.IntegerField()),
                ('description', models.CharField(default='', max_length=100)),
                ('mcc', models.IntegerField(default=-1)),
                ('hold', models.BooleanField(default=True)),
                ('amount', models.IntegerField(default=0)),
                ('operationAmount', models.IntegerField(default=0)),
                ('currency_code', models.IntegerField(default=980)),
                ('commissionRate', models.IntegerField(default=0)),
                ('cashbackAmount', models.IntegerField(default=0)),
                ('balance', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spendly_api.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spendly_api.user'),
        ),
    ]
