# Generated by Django 3.1.2 on 2020-10-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('acc_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254)),
                ('currency_code', models.IntegerField()),
                ('acc_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=50)),
                ('transaction_id', models.CharField(max_length=30)),
                ('time_since_epoch', models.IntegerField()),
                ('desc', models.CharField(max_length=100)),
                ('balance', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('merchant_category_code', models.IntegerField()),
                ('currency_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
