# Generated by Django 3.1.2 on 2020-10-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spendly_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='username',
        ),
    ]
