# Generated by Django 3.1.2 on 2020-10-18 18:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spendly_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user_email',
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='spendly_api.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='acc_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spendly_api.account'),
        ),
    ]
