# Generated by Django 3.1.2 on 2020-10-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendly_api', '0002_auto_20201018_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
