# Generated by Django 3.1.2 on 2020-10-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendly_api', '0003_auto_20201020_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
