# Generated by Django 3.1.2 on 2020-10-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spendly_api', '0004_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
